language: node_js
node_js:
  - 12
cache:
  directories:
  - node_modules # Cache the node_modules folder
script:
  - npm run build # Runs next build
  - npm run export # Generates the out directory
  - touch out/.nojekyll # Don't build the project using Jekyll
deploy:
  provider: pages # Deploy to GitHub Pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: out
  on:
    branch: master